(when (locate-library "helm")
  (require 'helm)

  (require 'helm-config)
  (helm-mode 1)
  (define-key global-map (kbd "C-x C-f") 'helm-find-files)
  (define-key global-map (kbd "C-x C-r") 'helm-recentf)
  (define-key global-map (kbd "C-x b")   'helm-buffers-list)
  (define-key helm-find-files-map (kbd "TAB") 'helm-execute-persistent-action)
)
(provide 'init_helm)
